// AuthZEN Access Evaluation as a gRPC contract for the internal (East-West)
// data path. It mirrors the JSON VSP Standard Contract (docs/design-v3 §3): the
// open-ended `properties` / `context` objects map to google.protobuf.Struct so
// arbitrary business attributes survive without a fixed schema, while the typed
// envelope keeps the hot internal path efficient (design-v3 §6.1).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/authzen/v1/authzen.proto

package authzenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "user" | "workload"
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_proto_authzen_v1_authzen_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "<domain>:<action>"
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_authzen_v1_authzen_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "<domain>:<entity>"
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_authzen_v1_authzen_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type EvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationRequest) Reset() {
	*x = EvaluationRequest{}
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationRequest) ProtoMessage() {}

func (x *EvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationRequest.ProtoReflect.Descriptor instead.
func (*EvaluationRequest) Descriptor() ([]byte, []int) {
	return file_proto_authzen_v1_authzen_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluationRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type DecisionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionToken) Reset() {
	*x = DecisionToken{}
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionToken) ProtoMessage() {}

func (x *DecisionToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionToken.ProtoReflect.Descriptor instead.
func (*DecisionToken) Descriptor() ([]byte, []int) {
	return file_proto_authzen_v1_authzen_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionToken) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DecisionToken) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type Obligation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "step_up" | "log"
	Details       *structpb.Struct       `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obligation) Reset() {
	*x = Obligation{}
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obligation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obligation) ProtoMessage() {}

func (x *Obligation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obligation.ProtoReflect.Descriptor instead.
func (*Obligation) Descriptor() ([]byte, []int) {
	return file_proto_authzen_v1_authzen_proto_rawDescGZIP(), []int{5}
}

func (x *Obligation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Obligation) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type EvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      bool                   `protobuf:"varint,1,opt,name=decision,proto3" json:"decision,omitempty"`
	DecisionToken *DecisionToken         `protobuf:"bytes,2,opt,name=decision_token,json=decisionToken,proto3" json:"decision_token,omitempty"` // set when decision == true
	Obligations   []*Obligation          `protobuf:"bytes,3,rep,name=obligations,proto3" json:"obligations,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,4,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authzen_v1_authzen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_proto_authzen_v1_authzen_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluationResponse) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *EvaluationResponse) GetDecisionToken() *DecisionToken {
	if x != nil {
		return x.DecisionToken
	}
	return nil
}

func (x *EvaluationResponse) GetObligations() []*Obligation {
	if x != nil {
		return x.Obligations
	}
	return nil
}

func (x *EvaluationResponse) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

var File_proto_authzen_v1_authzen_proto protoreflect.FileDescriptor

const file_proto_authzen_v1_authzen_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/authzen/v1/authzen.proto\x12\x0evsp.authzen.v1\x1a\x1cgoogle/protobuf/struct.proto\"f\n" +
	"\aSubject\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"U\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"g\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"\xdf\x01\n" +
	"\x11EvaluationRequest\x121\n" +
	"\asubject\x18\x01 \x01(\v2\x17.vsp.authzen.v1.SubjectR\asubject\x12.\n" +
	"\x06action\x18\x02 \x01(\v2\x16.vsp.authzen.v1.ActionR\x06action\x124\n" +
	"\bresource\x18\x03 \x01(\v2\x18.vsp.authzen.v1.ResourceR\bresource\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\"F\n" +
	"\rDecisionToken\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x05R\n" +
	"ttlSeconds\"S\n" +
	"\n" +
	"Obligation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x121\n" +
	"\adetails\x18\x02 \x01(\v2\x17.google.protobuf.StructR\adetails\"\xd5\x01\n" +
	"\x12EvaluationResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\bR\bdecision\x12D\n" +
	"\x0edecision_token\x18\x02 \x01(\v2\x1d.vsp.authzen.v1.DecisionTokenR\rdecisionToken\x12<\n" +
	"\vobligations\x18\x03 \x03(\v2\x1a.vsp.authzen.v1.ObligationR\vobligations\x12\x1f\n" +
	"\vreason_code\x18\x04 \x01(\tR\n" +
	"reasonCode2e\n" +
	"\x10AccessEvaluation\x12Q\n" +
	"\bEvaluate\x12!.vsp.authzen.v1.EvaluationRequest\x1a\".vsp.authzen.v1.EvaluationResponseBAZ?github.com/pmsbkhn/authorization-zta/proto/authzen/v1;authzenv1b\x06proto3"

var (
	file_proto_authzen_v1_authzen_proto_rawDescOnce sync.Once
	file_proto_authzen_v1_authzen_proto_rawDescData []byte
)

func file_proto_authzen_v1_authzen_proto_rawDescGZIP() []byte {
	file_proto_authzen_v1_authzen_proto_rawDescOnce.Do(func() {
		file_proto_authzen_v1_authzen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authzen_v1_authzen_proto_rawDesc), len(file_proto_authzen_v1_authzen_proto_rawDesc)))
	})
	return file_proto_authzen_v1_authzen_proto_rawDescData
}

var file_proto_authzen_v1_authzen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_authzen_v1_authzen_proto_goTypes = []any{
	(*Subject)(nil),            // 0: vsp.authzen.v1.Subject
	(*Action)(nil),             // 1: vsp.authzen.v1.Action
	(*Resource)(nil),           // 2: vsp.authzen.v1.Resource
	(*EvaluationRequest)(nil),  // 3: vsp.authzen.v1.EvaluationRequest
	(*DecisionToken)(nil),      // 4: vsp.authzen.v1.DecisionToken
	(*Obligation)(nil),         // 5: vsp.authzen.v1.Obligation
	(*EvaluationResponse)(nil), // 6: vsp.authzen.v1.EvaluationResponse
	(*structpb.Struct)(nil),    // 7: google.protobuf.Struct
}
var file_proto_authzen_v1_authzen_proto_depIdxs = []int32{
	7,  // 0: vsp.authzen.v1.Subject.properties:type_name -> google.protobuf.Struct
	7,  // 1: vsp.authzen.v1.Action.properties:type_name -> google.protobuf.Struct
	7,  // 2: vsp.authzen.v1.Resource.properties:type_name -> google.protobuf.Struct
	0,  // 3: vsp.authzen.v1.EvaluationRequest.subject:type_name -> vsp.authzen.v1.Subject
	1,  // 4: vsp.authzen.v1.EvaluationRequest.action:type_name -> vsp.authzen.v1.Action
	2,  // 5: vsp.authzen.v1.EvaluationRequest.resource:type_name -> vsp.authzen.v1.Resource
	7,  // 6: vsp.authzen.v1.EvaluationRequest.context:type_name -> google.protobuf.Struct
	7,  // 7: vsp.authzen.v1.Obligation.details:type_name -> google.protobuf.Struct
	4,  // 8: vsp.authzen.v1.EvaluationResponse.decision_token:type_name -> vsp.authzen.v1.DecisionToken
	5,  // 9: vsp.authzen.v1.EvaluationResponse.obligations:type_name -> vsp.authzen.v1.Obligation
	3,  // 10: vsp.authzen.v1.AccessEvaluation.Evaluate:input_type -> vsp.authzen.v1.EvaluationRequest
	6,  // 11: vsp.authzen.v1.AccessEvaluation.Evaluate:output_type -> vsp.authzen.v1.EvaluationResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_authzen_v1_authzen_proto_init() }
func file_proto_authzen_v1_authzen_proto_init() {
	if File_proto_authzen_v1_authzen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authzen_v1_authzen_proto_rawDesc), len(file_proto_authzen_v1_authzen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authzen_v1_authzen_proto_goTypes,
		DependencyIndexes: file_proto_authzen_v1_authzen_proto_depIdxs,
		MessageInfos:      file_proto_authzen_v1_authzen_proto_msgTypes,
	}.Build()
	File_proto_authzen_v1_authzen_proto = out.File
	file_proto_authzen_v1_authzen_proto_goTypes = nil
	file_proto_authzen_v1_authzen_proto_depIdxs = nil
}
