// AuthZEN Access Evaluation as a gRPC contract for the internal (East-West)
// data path. It mirrors the JSON VSP Standard Contract (docs/design-v3 §3): the
// open-ended `properties` / `context` objects map to google.protobuf.Struct so
// arbitrary business attributes survive without a fixed schema, while the typed
// envelope keeps the hot internal path efficient (design-v3 §6.1).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/authzen/v1/authzen.proto

package authzenv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessEvaluation_Evaluate_FullMethodName = "/vsp.authzen.v1.AccessEvaluation/Evaluate"
)

// AccessEvaluationClient is the client API for AccessEvaluation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccessEvaluation is the gRPC equivalent of POST /access/v1/evaluation.
type AccessEvaluationClient interface {
	Evaluate(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error)
}

type accessEvaluationClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessEvaluationClient(cc grpc.ClientConnInterface) AccessEvaluationClient {
	return &accessEvaluationClient{cc}
}

func (c *accessEvaluationClient) Evaluate(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationResponse)
	err := c.cc.Invoke(ctx, AccessEvaluation_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessEvaluationServer is the server API for AccessEvaluation service.
// All implementations must embed UnimplementedAccessEvaluationServer
// for forward compatibility.
//
// AccessEvaluation is the gRPC equivalent of POST /access/v1/evaluation.
type AccessEvaluationServer interface {
	Evaluate(context.Context, *EvaluationRequest) (*EvaluationResponse, error)
	mustEmbedUnimplementedAccessEvaluationServer()
}

// UnimplementedAccessEvaluationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessEvaluationServer struct{}

func (UnimplementedAccessEvaluationServer) Evaluate(context.Context, *EvaluationRequest) (*EvaluationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedAccessEvaluationServer) mustEmbedUnimplementedAccessEvaluationServer() {}
func (UnimplementedAccessEvaluationServer) testEmbeddedByValue()                          {}

// UnsafeAccessEvaluationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessEvaluationServer will
// result in compilation errors.
type UnsafeAccessEvaluationServer interface {
	mustEmbedUnimplementedAccessEvaluationServer()
}

func RegisterAccessEvaluationServer(s grpc.ServiceRegistrar, srv AccessEvaluationServer) {
	// If the following call panics, it indicates UnimplementedAccessEvaluationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessEvaluation_ServiceDesc, srv)
}

func _AccessEvaluation_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessEvaluationServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessEvaluation_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessEvaluationServer).Evaluate(ctx, req.(*EvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessEvaluation_ServiceDesc is the grpc.ServiceDesc for AccessEvaluation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessEvaluation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vsp.authzen.v1.AccessEvaluation",
	HandlerType: (*AccessEvaluationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _AccessEvaluation_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authzen/v1/authzen.proto",
}
